/* 
create table ##rowcounts (
tname nvarchar(100) , 
count int
) ; 
--select 'SELECT COUNT(*) FROM ' + name from sys.tables where type_desc = 'USER_TABLE'
--select 'execute #countrows @t=''' + name + '''' from sys.tables where type_desc = 'USER_TABLE'
--------------------------------------------------------------------------------------------------------------------------------------------------------
*/


create proc #countrows(@t nvarchar(200)) 
AS 
BEGIN 
	declare @sql  nvarchar(200) 
	declare @count int = 0 
	exec sp_executesql  @sql 
	
	set                                      @sql = 'SELECT COUNT(*), ''' + @t + ''' FROM ' + @t 
	execute sp_executesql @sql 

	set @sql = 'INSERT INTO ##ROWCOUNTS(count,tname ) SELECT COUNT(*), ''' + @t + ''' FROM ' + @t 
	execute sp_executesql @sql 
	

END
 
GO 

truncate table ##rowcounts

execute #countrows @t='oe_product_x_shipping_product_ext'
execute #countrows @t='np_donor_category_ext'
execute #countrows @t='co_request_origin_ext'
execute #countrows @t='ac_price_override_reason_ext'
execute #countrows @t='ab_abstract_status'
execute #countrows @t='wf_process'
execute #countrows @t='md_page_access'
execute #countrows @t='mk_mailing_type_ext'
execute #countrows @t='ad_insertion_order'
execute #countrows @t='co_degree_specialty'
execute #countrows @t='gr_congress_state_ext'
execute #countrows @t='ad_contract_ext'
execute #countrows @t='np_fund'
execute #countrows @t='am_accreditation_review'
execute #countrows @t='fw_group_column_privilege'
execute #countrows @t='cs_case'
execute #countrows @t='ac_media_type'
execute #countrows @t='oe_product_kit_component_ext'
execute #countrows @t='co_ondemand_purchase_data'
execute #countrows @t='md_report'
execute #countrows @t='ce_exam_fee'
execute #countrows @t='cs_case_fee_ext'
execute #countrows @t='su_request_type'
execute #countrows @t='gr_congress_state_staff'
execute #countrows @t='client_scouts_compliance_tracking'
execute #countrows @t='ac_merchant_account_ext'
execute #countrows @t='ev_location_x_co_individual'
execute #countrows @t='md_query'
execute #countrows @t='ac_invoice_terms_ext'
execute #countrows @t='ev_event_fee'
execute #countrows @t='sf_opportunity'
execute #countrows @t='cs_case_status'
execute #countrows @t='gr_congress_state_staff_ext'
execute #countrows @t='md_dynamic_form_panel'
execute #countrows @t='lm_list_header'
execute #countrows @t='md_web_x_link'
execute #countrows @t='lm_list_detail_ext'
execute #countrows @t='sf_sales_cycle_schedule'
execute #countrows @t='md_web_content_detail'
execute #countrows @t='ac_price_override_reason'
execute #countrows @t='oe_product_substitute'
execute #countrows @t='mb_member_type_x_mb_member_benefits'
execute #countrows @t='co_zone_ext'
execute #countrows @t='aw_award_media'
execute #countrows @t='ev_ribbon_ext'
execute #countrows @t='np_constituent_fund_recognition_level_ext'
execute #countrows @t='co_request_reason_ext'
execute #countrows @t='oe_warehouse'
execute #countrows @t='mb_association_x_oe_package_ext'
execute #countrows @t='co_country_mailing_label_format'
execute #countrows @t='co_fax_type'
execute #countrows @t='co_request_activity_type'
execute #countrows @t='ce_self_report_credit_ext'
execute #countrows @t='mb_committee_x_product_ext'
execute #countrows @t='aw_award_stage_ext'
execute #countrows @t='np_gift_type'
execute #countrows @t='lm_template_detail_ext'
execute #countrows @t='md_report_detail_list'
execute #countrows @t='ev_registrant_type'
execute #countrows @t='sf_user_x_commission_ext'
execute #countrows @t='co_chapter_x_customer_ext'
execute #countrows @t='ac_merchant_account'
execute #countrows @t='co_email_bounceback'
execute #countrows @t='can_post_codes'
execute #countrows @t='md_dynamic_profile_detail'
execute #countrows @t='ev_event'
execute #countrows @t='np_honor_memorial_info'
execute #countrows @t='co_customer_activity'
execute #countrows @t='am_surveyor_x_survey'
execute #countrows @t='co_request_role_ext'
execute #countrows @t='dg_topic'
execute #countrows @t='co_zone'
execute #countrows @t='co_organization_ext'
execute #countrows @t='fw_error_log'
execute #countrows @t='cs_case_status_ext'
execute #countrows @t='ts_scheduled_task'
execute #countrows @t='np_honor_memorial_letter'
execute #countrows @t='co_request_status'
execute #countrows @t='ad_rate_card_x_publication'
execute #countrows @t='ac_ar_period_scheduler_ext'
execute #countrows @t='oe_order_detail_term'
execute #countrows @t='cs_case_type'
execute #countrows @t='ce_course_x_event_ext'
execute #countrows @t='ac_return_ext'
execute #countrows @t='tm_project_task'
execute #countrows @t='md_web_default_pane'
execute #countrows @t='cs_case_expense'
execute #countrows @t='oe_inventory_received_ext'
execute #countrows @t='oe_tax_product'
execute #countrows @t='np_honor_memorial_notification'
execute #countrows @t='co_request_status_ext'
execute #countrows @t='cs_recommendation'
execute #countrows @t='ac_ar_period'
execute #countrows @t='tm_project_x_work_type'
execute #countrows @t='ac_multi_currency'
execute #countrows @t='np_recognition_level_change_log_ext'
execute #countrows @t='md_object_binary_serialize'
execute #countrows @t='co_chapter_x_customer'
execute #countrows @t='mb_association_x_oe_package'
execute #countrows @t='co_client'
execute #countrows @t='oe_product'
execute #countrows @t='co_chapter_x_member_type'
execute #countrows @t='co_degree_type'
execute #countrows @t='co_email_error_ext'
execute #countrows @t='ac_payment_info'
execute #countrows @t='co_note_ext'
execute #countrows @t='lm_template_header_ext'
execute #countrows @t='co_magnetmail_link_tracking_ext'
execute #countrows @t='co_response_type'
execute #countrows @t='ac_gl_account_default'
execute #countrows @t='oe_product_x_tax_ext'
execute #countrows @t='ac_invoice_message_ext'
execute #countrows @t='client_scouts_course_catalogue_x_co_customer'
execute #countrows @t='co_call2action_mailing_list_ext'
execute #countrows @t='md_report_request_key_list'
execute #countrows @t='ce_cert_program'
execute #countrows @t='co_keyword_category_ext'
execute #countrows @t='ce_course_fee'
execute #countrows @t='su_classification'
execute #countrows @t='ex_show_cancel_fee_ext'
execute #countrows @t='ac_payment_ext'
execute #countrows @t='oe_product_x_shipping_product'
execute #countrows @t='np_package'
execute #countrows @t='co_response_type_ext'
execute #countrows @t='md_query_export'
execute #countrows @t='aw_award_entry_x_co_document'
execute #countrows @t='ex_fee_type_ext'
execute #countrows @t='co_call2action_mailing_list'
execute #countrows @t='co_organization_type'
execute #countrows @t='co_survey_group'
execute #countrows @t='ac_lockbox_import'
execute #countrows @t='ce_course_participant_history_ext'
execute #countrows @t='aw_award_score'
execute #countrows @t='np_pledge_ext'
execute #countrows @t='lm_list_header_ext'
execute #countrows @t='co_task_ext'
execute #countrows @t='ev_event_location_room_type'
execute #countrows @t='mb_member_benefits'
execute #countrows @t='ac_invoice_message'
execute #countrows @t='ad_insertion_order_detail_additional'
execute #countrows @t='oe_order_detail_schedule_ext'
execute #countrows @t='co_request_role'
execute #countrows @t='fw_time_zone'
execute #countrows @t='co_survey_header'
execute #countrows @t='ce_course_credit_ext'
execute #countrows @t='co_keyword_category'
execute #countrows @t='cs_case_type_ext'
execute #countrows @t='ev_registrant_session_ext'
execute #countrows @t='ex_show_cancel_fee'
execute #countrows @t='ac_payment_detail_ext'
execute #countrows @t='ev_registrant_ribbon_ext'
execute #countrows @t='mb_committee_x_event_ext'
execute #countrows @t='sf_staff_commission_ext'
execute #countrows @t='md_search_table_x_group'
execute #countrows @t='ab_author_type_ext'
execute #countrows @t='sf_sales_cycle_schedule_ext'
execute #countrows @t='lm_template_detail'
execute #countrows @t='client_scouts_member_account'
execute #countrows @t='md_wizard_form'
execute #countrows @t='aw_award_entry_contact'
execute #countrows @t='ex_booth_number_ext'
execute #countrows @t='co_organization_dem_ext'
execute #countrows @t='ex_fee_type'
execute #countrows @t='ev_event_location_room'
execute #countrows @t='ec_shopping_cart'
execute #countrows @t='ac_order_detail_x_credit_detail_ext'
execute #countrows @t='mb_association_x_user'
execute #countrows @t='ac_lockbox_header'
execute #countrows @t='oe_product_prerequisite_ext'
execute #countrows @t='oe_product_type'
execute #countrows @t='ac_invoice_detail'
execute #countrows @t='aw_award_entry_contact_type'
execute #countrows @t='fw_synchronization_history'
execute #countrows @t='md_table_list_column'
execute #countrows @t='jb_job_bank_ext'
execute #countrows @t='md_web_section_default'
execute #countrows @t='co_related_association_ext'
execute #countrows @t='ac_invoice_product_temp'
execute #countrows @t='fw_user_x_md_object'
execute #countrows @t='mk_mailing_list_type_ext'
execute #countrows @t='np_campaign_ext'
execute #countrows @t='ev_ribbon'
execute #countrows @t='cs_case_source_ext'
execute #countrows @t='ev_session'
execute #countrows @t='am_committee_surveyor_team_evaluation_ext'
execute #countrows @t='mq_address_log'
execute #countrows @t='ac_refund_detail'
execute #countrows @t='aw_award_score_ext'
execute #countrows @t='mb_committee_x_product'
execute #countrows @t='ac_refund_ext'
execute #countrows @t='co_individual_x_organization'
execute #countrows @t='np_corp_matching_ext'
execute #countrows @t='np_premium_pick'
execute #countrows @t='co_customer_activity_ext'
execute #countrows @t='tm_billing_period_detail'
execute #countrows @t='ev_event_faculty_ext'
execute #countrows @t='md_css_file'
execute #countrows @t='ab_author_type'
execute #countrows @t='oe_claim_detail_ext'
execute #countrows @t='mb_membership_x_ac_invoice'
execute #countrows @t='co_individual_ext'
execute #countrows @t='ex_priority_point_detail'
execute #countrows @t='di_document'
execute #countrows @t='ce_self_report_credit'
execute #countrows @t='oe_product_kit_component'
execute #countrows @t='cs_case_x_case_ext'
execute #countrows @t='ce_course_x_program'
execute #countrows @t='su_job_function'
execute #countrows @t='ce_individual_desig'
execute #countrows @t='mb_member_type_x_member_status_ext'
execute #countrows @t='np_fund_ext'
execute #countrows @t='ac_order_detail_x_credit_detail'
execute #countrows @t='co_organization_type_ext'
execute #countrows @t='np_premium_selection'
execute #countrows @t='ce_waiver'
execute #countrows @t='ce_exam_import'
execute #countrows @t='oe_product_prerequisite'
execute #countrows @t='co_assignment'
execute #countrows @t='ce_individual_desig_ext'
execute #countrows @t='cs_case_x_document'
execute #countrows @t='client_scouts_experimental_registration'
execute #countrows @t='co_customer_alias'
execute #countrows @t='np_gift_type_ext'
execute #countrows @t='sf_staff_commission'
execute #countrows @t='co_customer_activity_archive'
execute #countrows @t='su_subscription'
execute #countrows @t='ev_event_faculty_x_co_document'
execute #countrows @t='co_zone_zip_ext'
execute #countrows @t='fw_department'
execute #countrows @t='mb_calculation_result'
execute #countrows @t='co_keyword'
execute #countrows @t='client_scouts_online_transaction_error_log'
execute #countrows @t='fw_form_change_log'
execute #countrows @t='np_honor_memorial_info_ext'
execute #countrows @t='ev_event_faculty_x_co_document_ext'
execute #countrows @t='ce_course_ext'
execute #countrows @t='np_match_program_ext'
execute #countrows @t='ac_deferral'
execute #countrows @t='co_region'
execute #countrows @t='ex_booth_x_complementary_products'
execute #countrows @t='np_honor_memorial_letter_ext'
execute #countrows @t='aw_award_judge_ext'
execute #countrows @t='co_relationship_type_ext'
execute #countrows @t='md_dynamic_search'
execute #countrows @t='mb_committee_x_dg_topic_group_ext'
execute #countrows @t='ev_registrant_location_room_ext'
execute #countrows @t='md_web_search_agent_result'
execute #countrows @t='fw_synchronization_detail'
execute #countrows @t='ev_event_credit_ext'
execute #countrows @t='cs_case_x_document_ext'
execute #countrows @t='md_dynamic_form_substitute'
execute #countrows @t='oe_merchandise_ext'
execute #countrows @t='client_scouts_online_user_exception_log'
execute #countrows @t='np_honor_memorial_notification_ext'
execute #countrows @t='ev_event_fee_ext'
execute #countrows @t='lm_template_header'
execute #countrows @t='co_zone_zip'
execute #countrows @t='mb_committee_x_document_ext'
execute #countrows @t='ce_course_dates'
execute #countrows @t='cs_category'
execute #countrows @t='ac_payment'
execute #countrows @t='su_subscription_issue'
execute #countrows @t='ac_lockbox_exception'
execute #countrows @t='np_package_ext'
execute #countrows @t='tm_project'
execute #countrows @t='ev_event_file_attachment'
execute #countrows @t='tm_billing'
execute #countrows @t='co_individual_dem_ext'
execute #countrows @t='co_request_reason'
execute #countrows @t='ex_exhibitor_booth_shared_ext'
execute #countrows @t='mb_committee_x_event'
execute #countrows @t='np_pledge'
execute #countrows @t='co_customer_x_document_ext'
execute #countrows @t='ec_payment'
execute #countrows @t='np_premium_ext'
execute #countrows @t='ev_registrant_ribbon'
execute #countrows @t='mb_member_type_dependency_ext'
execute #countrows @t='ev_event_file_attachment_ext'
execute #countrows @t='mb_committee_x_dg_topic_group'
execute #countrows @t='ad_agency'
execute #countrows @t='ev_registrant_location_room'
execute #countrows @t='ex_booth_fee'
execute #countrows @t='ev_track_fee'
execute #countrows @t='co_customer_x_related_association_ext'
execute #countrows @t='mk_mailing_list_ext'
execute #countrows @t='oe_product_ext'
execute #countrows @t='np_premium_pick_ext'
execute #countrows @t='ad_insertion_order_detail'
execute #countrows @t='fw_change_log'
execute #countrows @t='md_web_posting'
execute #countrows @t='ac_ar_fiscal_year'
execute #countrows @t='ac_gl_account_default_ext'
execute #countrows @t='ev_event_cancel_fee_ext'
execute #countrows @t='co_request_correspondence_template_ext'
execute #countrows @t='oe_installment_milestone_ext'
execute #countrows @t='mb_committee_x_document'
execute #countrows @t='md_web_posting_x_posting_ext'
execute #countrows @t='su_title'
execute #countrows @t='ac_refund_detail_ext'
execute #countrows @t='ce_course_credit'
execute #countrows @t='ce_individual_business'
execute #countrows @t='client_scouts_mb_member_type_x_role'
execute #countrows @t='np_premium_selection_ext'
execute #countrows @t='np_constituent_fund_recognition_level'
execute #countrows @t='co_address'
execute #countrows @t='wf_workflow_ext'
execute #countrows @t='tm_time'
execute #countrows @t='ad_agency_ext'
execute #countrows @t='ex_show_x_priority_point_type_ext'
execute #countrows @t='co_customer_x_document'
execute #countrows @t='np_recognition_type_ext'
execute #countrows @t='ac_credit_detail'
execute #countrows @t='mb_member_type_dependency'
execute #countrows @t='ev_event_location_ext'
execute #countrows @t='md_table_keep_data'
execute #countrows @t='ab_abstract_submission'
execute #countrows @t='ac_currency_ext'
execute #countrows @t='co_assignment_role'
execute #countrows @t='fw_error_log_archive'
execute #countrows @t='ev_registrant_group'
execute #countrows @t='ce_individual_license_ext'
execute #countrows @t='co_customer_x_related_association'
execute #countrows @t='tm_billing_ext'
execute #countrows @t='ce_course_participant_ext'
execute #countrows @t='md_web_search_agent'
execute #countrows @t='tt_request_ext'
execute #countrows @t='oe_shipping_region'
execute #countrows @t='cs_category_ext'
execute #countrows @t='ts_report_task'
execute #countrows @t='oe_price_ext'
execute #countrows @t='mq_log_message'
execute #countrows @t='oe_order'
execute #countrows @t='ev_event_location_room_ext'
execute #countrows @t='cs_decision'
execute #countrows @t='mb_committee_minutes'
execute #countrows @t='aw_award_entry'
execute #countrows @t='md_upgrade_deleted_metadata'
execute #countrows @t='mq_log_message_error'
execute #countrows @t='co_fax_error'
execute #countrows @t='aw_award_fee_category_ext'
execute #countrows @t='ac_adjustment_ext'
execute #countrows @t='wf_process_x_action'
execute #countrows @t='mq_log_message_recipient'
execute #countrows @t='cm_group_item_link'
execute #countrows @t='ev_event_setup_category_budget'
execute #countrows @t='tt_request'
execute #countrows @t='am_surveyor_x_document'
execute #countrows @t='client_scouts_organization_sub_type'
execute #countrows @t='ce_product_credit_ext'
execute #countrows @t='ev_event_substitution_fee_ext'
execute #countrows @t='ac_gl_account_type'
execute #countrows @t='ev_event_setup_category_budget_ext'
execute #countrows @t='tm_time_x_invoice_detail'
execute #countrows @t='ac_deferral_x_misc_transaction_ext'
execute #countrows @t='ad_insertion_order_discount'
execute #countrows @t='ac_deferral_x_misc_transaction'
execute #countrows @t='co_note'
execute #countrows @t='co_chapter_x_member_type_ext'
execute #countrows @t='ev_track_fee_ext'
execute #countrows @t='md_table_list_table'
execute #countrows @t='mb_membership_proxy'
execute #countrows @t='gn_applicant_ext'
execute #countrows @t='co_state_territory_ext'
execute #countrows @t='mq_messaging_job_attachment'
execute #countrows @t='ad_insertion_order_detail_ext'
execute #countrows @t='ev_event_category_ext'
execute #countrows @t='ad_contract_x_contact_ext'
execute #countrows @t='co_request_correspondence_template'
execute #countrows @t='aw_award_fee'
execute #countrows @t='ws_web_service_method_node'
execute #countrows @t='cs_decision_ext'
execute #countrows @t='gn_applicant_review'
execute #countrows @t='ac_adjustment_detail_ext'
execute #countrows @t='mk_mailing_list_detail_ext'
execute #countrows @t='md_web_posting_document_ext'
execute #countrows @t='mq_messaging_job_report'
execute #countrows @t='ev_event_speaker_attachment'
execute #countrows @t='oe_order_detail_term_ext'
execute #countrows @t='cs_press_release'
execute #countrows @t='ev_event_substitution_fee'
execute #countrows @t='gn_applicant_review_ext'
execute #countrows @t='ev_track'
execute #countrows @t='ev_event_speaker_attachment_ext'
execute #countrows @t='mb_member_dues_history'
execute #countrows @t='ev_housing_ext'
execute #countrows @t='wf_action_ext'
execute #countrows @t='co_prefix'
execute #countrows @t='oe_installment_milestone'
execute #countrows @t='ex_complementary_products_ext'
execute #countrows @t='co_country'
execute #countrows @t='md_upgrade_script'
execute #countrows @t='co_chapter_status_ext'
execute #countrows @t='ev_event_speaker_ext'
execute #countrows @t='ce_course_x_location_ext'
execute #countrows @t='ev_registrant'
execute #countrows @t='ac_deferral_ext'
execute #countrows @t='ex_booth_category_ext'
execute #countrows @t='ce_exam_score_history'
execute #countrows @t='oe_purchase_order_ext'
execute #countrows @t='ev_registration_dem'
execute #countrows @t='gr_congress_staff_ext'
execute #countrows @t='ce_individual_business_ext'
execute #countrows @t='ex_show'
execute #countrows @t='ad_advertiser_ext'
execute #countrows @t='gn_applicant_status_ext'
execute #countrows @t='client_avectra_informz_email_tracking'
execute #countrows @t='np_recognition_level_change_log'
execute #countrows @t='client_scouts_course_catalogue'
execute #countrows @t='ws_web_service_method'
execute #countrows @t='np_soft_credit_type_ext'
execute #countrows @t='co_relationship_type'
execute #countrows @t='ce_exam_import_ext'
execute #countrows @t='cs_press_release_ext'
execute #countrows @t='ts_task_parameter'
execute #countrows @t='co_demographic_question_type'
execute #countrows @t='gn_applicant_x_co_document'
execute #countrows @t='md_web_posting_category'
execute #countrows @t='ec_shopping_cart_items'
execute #countrows @t='su_subscription_ext'
execute #countrows @t='client_avectra_informz_email_tracking_ext'
execute #countrows @t='ev_registrant_x_ac_invoice'
execute #countrows @t='ev_event_speaker_handout_ext'
execute #countrows @t='ac_project_ext'
execute #countrows @t='ac_invoice_terms'
execute #countrows @t='oe_price_attribute_ext'
execute #countrows @t='gn_applicant_x_co_document_ext'
execute #countrows @t='client_avectra_informz_unsubscribe'
execute #countrows @t='md_dynamic_form_control'
execute #countrows @t='client_scouts_course_catalogue_x_course_catalogue'
execute #countrows @t='ex_booth_fee_ext'
execute #countrows @t='ev_registrant_room_request_ext'
execute #countrows @t='co_customer_history_ext'
execute #countrows @t='ac_proforma_process_header_ext'
execute #countrows @t='ac_credit'
execute #countrows @t='co_state_territory'
execute #countrows @t='np_match_program'
execute #countrows @t='gn_distribution'
execute #countrows @t='client_avectra_informz_unsubscribe_ext'
execute #countrows @t='oe_fulfillment_exception'
execute #countrows @t='ev_location_room_type'
execute #countrows @t='md_cache_clear_status'
execute #countrows @t='ev_location'
execute #countrows @t='co_customer_x_address_ext'
execute #countrows @t='ev_event_speaker_honorarium_ext'
execute #countrows @t='np_soft_credit_type'
execute #countrows @t='co_email_error'
execute #countrows @t='am_survey_x_document'
execute #countrows @t='aw_award_fee_category'
execute #countrows @t='ex_exhibitor_x_co_document_ext'
execute #countrows @t='gn_distribution_ext'
execute #countrows @t='ex_show_sponsor_fee_ext'
execute #countrows @t='cs_case_x_case'
execute #countrows @t='np_appeal_ext'
execute #countrows @t='oe_product_kit'
execute #countrows @t='ev_event_speaker_honorarium_type'
execute #countrows @t='fw_persona'
execute #countrows @t='client_scouts_recognition_list'
execute #countrows @t='fw_address_standard_error'
execute #countrows @t='ex_booth_personnel_ext'
execute #countrows @t='client_scouts_role_x_reports'
execute #countrows @t='cs_recommendation_ext'
execute #countrows @t='ev_event_speaker_presentation'
execute #countrows @t='ab_abstract_reviewer_ext'
execute #countrows @t='ad_insertion_order_discount_ext'
execute #countrows @t='ev_event_speaker_honorarium_type_ext'
execute #countrows @t='co_customer_x_fax'
execute #countrows @t='md_cache_clear_flag'
execute #countrows @t='ad_contract_role_ext'
execute #countrows @t='ev_event_session_room_ext'
execute #countrows @t='co_customer_history'
execute #countrows @t='ce_exam_grader_ext'
execute #countrows @t='ws_web_service'
execute #countrows @t='mk_mailing_list_exclude_ext'
execute #countrows @t='oe_price_term_ext'
execute #countrows @t='ex_booth_type_ext'
execute #countrows @t='co_chapter_x_dg_topic_group'
execute #countrows @t='co_document_classification'
execute #countrows @t='md_wizard_progress'
execute #countrows @t='ac_batch_ext'
execute #countrows @t='mb_member_dues_renewal_process_header'
execute #countrows @t='gn_program_contact'
execute #countrows @t='ab_abstract_reviewer_response_ext'
execute #countrows @t='ev_event_speaker_presentation_ext'
execute #countrows @t='mb_member_dues_renewal_process_ext'
execute #countrows @t='oe_shipping_carrier_ext'
execute #countrows @t='md_lookup'
execute #countrows @t='wf_process_ext'
execute #countrows @t='ev_event_session_room_x_setup_ext'
execute #countrows @t='ce_course_participant_history'
execute #countrows @t='ex_complementary_products_fee_ext'
execute #countrows @t='ts_result_handler'
execute #countrows @t='gn_program_contact_ext'
execute #countrows @t='co_chapter_type_ext'
execute #countrows @t='co_interest_code'
execute #countrows @t='co_demographic_change_log'
execute #countrows @t='ce_exam_x_location_ext'
execute #countrows @t='co_website'
execute #countrows @t='ex_show_ext'
execute #countrows @t='np_product_code_ext'
execute #countrows @t='gr_congress_ext'
execute #countrows @t='ws_web_service_method_server'
execute #countrows @t='ev_location_setup_category'
execute #countrows @t='gn_program_expense'
execute #countrows @t='mk_mailing_list_type'
execute #countrows @t='ce_certificant'
execute #countrows @t='fw_user_x_option'
execute #countrows @t='ab_abstract_submission_ext'
execute #countrows @t='ev_event_speaker_type_ext'
execute #countrows @t='ac_payment_credit_temp'
execute #countrows @t='fw_entity'
execute #countrows @t='ce_course_participant'
execute #countrows @t='co_address_ext'
execute #countrows @t='gn_program_expense_ext'
execute #countrows @t='oe_inventory_x_warehouse_ext'
execute #countrows @t='mb_committee_position_ext'
execute #countrows @t='ac_batch_exception'
execute #countrows @t='ac_invoice_additional_temp'
execute #countrows @t='md_column_custom_ext'
execute #countrows @t='ad_invoice_group_ext'
execute #countrows @t='co_demographic_x_fw_group'
execute #countrows @t='gn_program_expense_type'
execute #countrows @t='md_workflow_task'
execute #countrows @t='ce_course_type'
execute #countrows @t='ab_author_ext'
execute #countrows @t='fw_entity_x_user'
execute #countrows @t='ev_event_sponsor_ext'
execute #countrows @t='oe_product_affiliation_commission_ext'
execute #countrows @t='ac_batch_x_fw_group_ext'
execute #countrows @t='lm_data_import'
execute #countrows @t='ac_proforma_process_invoice_ext'
execute #countrows @t='am_accreditation_status'
execute #countrows @t='ex_sponsor_contact_ext'
execute #countrows @t='ex_sponsor_contact'
execute #countrows @t='gn_program_expense_type_ext'
execute #countrows @t='ce_provider'
execute #countrows @t='cs_case_expense_ext'
execute #countrows @t='ex_exhibitor_booth_ext'
execute #countrows @t='ex_show_x_booth_ext'
execute #countrows @t='ex_sponsor_x_co_document_ext'
execute #countrows @t='gr_congress_fed'
execute #countrows @t='ex_complementary_products'
execute #countrows @t='oe_inventory_received'
execute #countrows @t='oe_claim_detail'
execute #countrows @t='gn_program_ext'
execute #countrows @t='su_subscription_renewal_process_ext'
execute #countrows @t='oe_product_category_ext'
execute #countrows @t='md_web_album_photo'
execute #countrows @t='mb_member_type_x_member_status'
execute #countrows @t='ev_registrant_session'
execute #countrows @t='mb_committee_x_customer_ext'
execute #countrows @t='ev_event_sponsor_fee_ext'
execute #countrows @t='am_survey_x_document_ext'
execute #countrows @t='co_correspondence_template'
execute #countrows @t='gn_applicant_status'
execute #countrows @t='ce_course_prerequisite_ext'
execute #countrows @t='gn_program_funding'
execute #countrows @t='ex_show_sponsor_fee'
execute #countrows @t='tm_work_type_ext'
execute #countrows @t='ce_provider_electronic_file_ext'
execute #countrows @t='sf_user_x_commission'
execute #countrows @t='ce_exam_score_ext'
execute #countrows @t='ac_payment_counter'
execute #countrows @t='gn_program_funding_ext'
execute #countrows @t='su_subscription_renewal_process_detail'
execute #countrows @t='ev_event_sponsor_type_ext'
execute #countrows @t='ce_ceu_credit_generate_header'
execute #countrows @t='co_request_priority'
execute #countrows @t='sf_opportunity_history_ext'
execute #countrows @t='ex_exhibitor_x_co_document'
execute #countrows @t='ts_report_email_handler'
execute #countrows @t='gn_program_x_co_document'
execute #countrows @t='ec_shopping_cart_ext'
execute #countrows @t='oe_product_category'
execute #countrows @t='ac_ar_period_ext'
execute #countrows @t='co_customer_alias_ext'
execute #countrows @t='co_demographic_group_x_item_ext'
execute #countrows @t='ce_product_credit'
execute #countrows @t='md_cache_setup'
execute #countrows @t='ev_event_speaker_honorarium'
execute #countrows @t='wf_process_x_action_ext'
execute #countrows @t='ex_booth_category'
execute #countrows @t='co_customer_ext'
execute #countrows @t='gn_program_x_co_document_ext'
execute #countrows @t='ac_lockbox_import_ext'
execute #countrows @t='mb_member_dues_renewal_batch_log_ext'
execute #countrows @t='ev_event_staff_ext'
execute #countrows @t='ev_event_sponsor'
execute #countrows @t='ce_provider_electronic_file'
execute #countrows @t='mk_mailing_type'
execute #countrows @t='gr_congress_committee_ext'
execute #countrows @t='ac_lockbox_header_ext'
execute #countrows @t='ad_advertisement_size_ext'
execute #countrows @t='fw_user'
execute #countrows @t='mb_member_type'
execute #countrows @t='co_messaging'
execute #countrows @t='tm_work_type_x_billing_ext'
execute #countrows @t='co_magnetmail_email_tracking'
execute #countrows @t='fw_group'
execute #countrows @t='co_email_ext'
execute #countrows @t='md_query_sub_detail'
execute #countrows @t='oe_product_package_ext'
execute #countrows @t='md_web_cssclass'
execute #countrows @t='co_zip_code_ext'
execute #countrows @t='ac_gl_account_ext'
execute #countrows @t='ev_event_staff_type_ext'
execute #countrows @t='md_search_column'
execute #countrows @t='ad_advertisement_size'
execute #countrows @t='mb_membership'
execute #countrows @t='client_scouts_individual_x_reference'
execute #countrows @t='oe_fulfillment_inventory_cogs_ext'
execute #countrows @t='mb_committee_type_ext'
execute #countrows @t='co_address_change_log'
execute #countrows @t='ce_exam_score'
execute #countrows @t='ev_event_location_room_type_ext'
execute #countrows @t='gr_congress_committee'
execute #countrows @t='am_accreditation_type'
execute #countrows @t='co_source_code'
execute #countrows @t='ac_adjustment'
execute #countrows @t='am_accreditation'
execute #countrows @t='ac_misc_transaction_ext'
execute #countrows @t='ac_multi_currency_ext'
execute #countrows @t='ad_contract_status'
execute #countrows @t='su_subscription_renewal_process_detail_ext'
execute #countrows @t='ev_event_type_ext'
execute #countrows @t='co_suffix'
execute #countrows @t='oe_product_affiliation'
execute #countrows @t='md_query_x_group_deny'
execute #countrows @t='oe_order_detail_additional'
execute #countrows @t='ce_individual_x_course'
execute #countrows @t='ac_customer_payment_info'
execute #countrows @t='ev_event_session_room'
execute #countrows @t='sf_opportunity_ext'
execute #countrows @t='np_campaign'
execute #countrows @t='ev_event_volunteer'
execute #countrows @t='ex_sponsor_x_co_document'
execute #countrows @t='ac_proforma_process_invoice'
execute #countrows @t='mq_messaging_job'
execute #countrows @t='ts_error_log'
execute #countrows @t='md_workflow_task_log'
execute #countrows @t='ev_event_volunteer_ext'
execute #countrows @t='oe_product_x_tax'
execute #countrows @t='oe_shipping_carrier'
execute #countrows @t='ev_session_fee_ext'
execute #countrows @t='ev_sponsor_x_document_ext'
execute #countrows @t='tm_work_type_x_billing'
execute #countrows @t='gr_congress_fed_committee_roster'
execute #countrows @t='ce_waiver_ext'
execute #countrows @t='ce_individual_license'
execute #countrows @t='md_web_posting_rating_ext'
execute #countrows @t='ac_misc_transaction_detail_ext'
execute #countrows @t='ce_certificant_status_ext'
execute #countrows @t='co_address_change_log_reason'
execute #countrows @t='co_nf_od_activity'
execute #countrows @t='ev_event_volunteer_type'
execute #countrows @t='md_cache_setup_related'
execute #countrows @t='tm_category_ext'
execute #countrows @t='md_upgrade_log'
execute #countrows @t='oe_fulfillment_group_ext'
execute #countrows @t='aw_award_fee_ext'
execute #countrows @t='co_institution_ext'
execute #countrows @t='ev_event_volunteer_type_ext'
execute #countrows @t='mb_member_status_ext'
execute #countrows @t='co_request_priority_ext'
execute #countrows @t='ex_booth_type'
execute #countrows @t='ac_refund_counter'
execute #countrows @t='md_query_sub'
execute #countrows @t='oe_fulfillment_bpa_ext'
execute #countrows @t='sf_opportunity_stage'
execute #countrows @t='su_fulfillment_action_ext'
execute #countrows @t='ce_course_prerequisite'
execute #countrows @t='oe_price_prorate'
execute #countrows @t='ev_event_location_room_block'
execute #countrows @t='am_committee_surveyor_team_evaluation'
execute #countrows @t='ev_event_wait_list'
execute #countrows @t='oe_price_prorate_ext'
execute #countrows @t='oe_inventory_x_warehouse'
execute #countrows @t='md_dynamic_form_child_x_group'
execute #countrows @t='md_object_data'
execute #countrows @t='tm_billing_period_ext'
execute #countrows @t='ev_event_wait_list_ext'
execute #countrows @t='tm_category'
execute #countrows @t='tm_work_type'
execute #countrows @t='co_messaging_ext'
execute #countrows @t='md_privilege'
execute #countrows @t='gr_congress_staff'
execute #countrows @t='mb_committee_ext'
execute #countrows @t='co_institution'
execute #countrows @t='oe_product_kit_ext'
execute #countrows @t='ac_installment_billing_exception'
execute #countrows @t='ad_advertisement_position_ext'
execute #countrows @t='co_prefix_ext'
execute #countrows @t='np_wealthengine_results'
execute #countrows @t='co_address_type'
execute #countrows @t='oe_price_attribute'
execute #countrows @t='ts_dues_renewal_report_task'
execute #countrows @t='co_zip_code'
execute #countrows @t='co_address_change_log_ext'
execute #countrows @t='ce_requirement_group_ext'
execute #countrows @t='md_web_faq'
execute #countrows @t='ad_advertiser_contact_ext'
execute #countrows @t='md_form_link'
execute #countrows @t='ce_course'
execute #countrows @t='mb_member_dues_renewal_process_header_ext'
execute #countrows @t='ce_exam_material'
execute #countrows @t='mk_mailing_list_exclude'
execute #countrows @t='md_dynamic_form_detail'
execute #countrows @t='co_address_bad_type'
execute #countrows @t='ad_advertisement_color'
execute #countrows @t='co_customer_activity_archive_ext'
execute #countrows @t='su_subscription_renewal_process_header_ext'
execute #countrows @t='ac_gl_account_type_ext'
execute #countrows @t='ev_file_type'
execute #countrows @t='mb_member_drop_process_header'
execute #countrows @t='ad_advertisement_position'
execute #countrows @t='np_recognition_type'
execute #countrows @t='ev_track_cancel_fee_ext'
execute #countrows @t='sf_opportunity_type_ext'
execute #countrows @t='ev_evaluation_ext'
execute #countrows @t='wf_action'
execute #countrows @t='fw_option'
execute #countrows @t='tm_resource_rate_ext'
execute #countrows @t='sysdiagrams'
execute #countrows @t='ex_show_sponsor_ext'
execute #countrows @t='ad_advertisement_color_ext'
execute #countrows @t='sf_commission_schedule'
execute #countrows @t='oe_bundle_ext'
execute #countrows @t='ac_gl_account'
execute #countrows @t='ev_sponsor_contact'
execute #countrows @t='fw_taxonomy_header_ext'
execute #countrows @t='md_column'
execute #countrows @t='ex_exhibitor_product_ext'
execute #countrows @t='ev_event_sponsor_type'
execute #countrows @t='ev_location_ext'
execute #countrows @t='oe_shipping_region_ext'
execute #countrows @t='ce_requirement_group'
execute #countrows @t='ev_sponsor_contact_ext'
execute #countrows @t='gr_congress_state'
execute #countrows @t='ce_exam_material_ext'
execute #countrows @t='ad_advertiser_contact'
execute #countrows @t='ev_event_fee_category_ext'
execute #countrows @t='am_accreditation_x_customer'
execute #countrows @t='ev_location_role'
execute #countrows @t='ce_provider_ext'
execute #countrows @t='ad_advertisement'
execute #countrows @t='oe_fulfillment_ext'
execute #countrows @t='md_web_posting_category_ext'
execute #countrows @t='cs_case_source'
execute #countrows @t='ev_event_sponsor_fee'
execute #countrows @t='ac_misc_transaction'
execute #countrows @t='client_scouts_volunteer_screening_reference'
execute #countrows @t='tm_resource_rate'
execute #countrows @t='md_web_section'
execute #countrows @t='ev_location_role_ext'
execute #countrows @t='co_assignment_x_customer_ext'
execute #countrows @t='co_suffix_ext'
execute #countrows @t='oe_order_installment_generate_header'
execute #countrows @t='ad_contract_role'
execute #countrows @t='co_contact_response'
execute #countrows @t='su_fulfillment'
execute #countrows @t='sf_territory_assignment_ext'
execute #countrows @t='co_degree'
execute #countrows @t='ad_advertiser_x_agency_ext'
execute #countrows @t='ev_event_type'
execute #countrows @t='cm_group'
execute #countrows @t='su_industry_ext'
execute #countrows @t='md_wizard_step'
execute #countrows @t='ev_location_room'
execute #countrows @t='ev_event_x_registrant_type_ext'
execute #countrows @t='su_subscription_renewal_process_header'
execute #countrows @t='ev_sponsor_x_document'
execute #countrows @t='ex_booth_x_complementary_products_ext'
execute #countrows @t='am_surveyor_type_ext'
execute #countrows @t='ex_booth_x_ac_invoice_detail_ext'
execute #countrows @t='ev_event_fee_category'
execute #countrows @t='co_address_hold_type'
execute #countrows @t='tm_billing_period_detail_ext'
execute #countrows @t='ev_location_room_ext'
execute #countrows @t='ac_payment_method_ext'
execute #countrows @t='ac_period_close_exception'
execute #countrows @t='md_column_custom'
execute #countrows @t='co_phone_ext'
execute #countrows @t='ac_invoice_discount_temp'
execute #countrows @t='su_fulfillment_action'
execute #countrows @t='co_degree_ext'
execute #countrows @t='md_sync_sql_log'
execute #countrows @t='ab_abstract_reviewer_x_submission_ext'
execute #countrows @t='ad_advertiser_x_agency'
execute #countrows @t='co_call2action_campaign'
execute #countrows @t='ac_ar_fiscal_year_ext'
execute #countrows @t='ab_abstract_category_ext'
execute #countrows @t='ev_location_room_type_ext'
execute #countrows @t='am_survey_scope'
execute #countrows @t='np_planned_giving_ext'
execute #countrows @t='co_survey_response_status'
execute #countrows @t='md_web_content'
execute #countrows @t='ex_booth_x_ac_invoice_detail'
execute #countrows @t='mb_member_dues_renewal_process_detail_ext'
execute #countrows @t='co_chapter_status'
execute #countrows @t='co_call2action_ext'
execute #countrows @t='tm_billing_period'
execute #countrows @t='client_scouts_volunteer_screening'
execute #countrows @t='ev_room_type_x_setup_category'
execute #countrows @t='ad_contract_counter'
execute #countrows @t='md_dedup_table'
execute #countrows @t='mb_member_dues_renewal_process_detail'
execute #countrows @t='ac_proforma_process_header'
execute #countrows @t='ad_advertiser'
execute #countrows @t='ev_session_cancel_fee_ext'
execute #countrows @t='sf_opportunity_stage_ext'
execute #countrows @t='co_email_error_archive'
execute #countrows @t='ad_contract'
execute #countrows @t='ev_room_type_x_setup_category_ext'
execute #countrows @t='co_customer_x_phone'
execute #countrows @t='tm_expense_type_ext'
execute #countrows @t='oe_bundle_component_ext'
execute #countrows @t='mb_member_status'
execute #countrows @t='ev_housing'
execute #countrows @t='fw_taxonomy_category_ext'
execute #countrows @t='gn_applicant'
execute #countrows @t='ex_exhibitor_product_type_ext'
execute #countrows @t='ts_dues_renewal_invoice_task'
execute #countrows @t='mb_dues_calc_variables'
execute #countrows @t='ce_course_dates_ext'
execute #countrows @t='np_major_gift_ext'
execute #countrows @t='ab_abstract_category'
execute #countrows @t='ev_location_room_x_setup'
execute #countrows @t='mb_membership_ext'
execute #countrows @t='sf_opportunity_history'
execute #countrows @t='oe_fulfillment_group'
execute #countrows @t='mb_membership_terminate_reason_ext'
execute #countrows @t='mb_committee_type'
execute #countrows @t='co_assignment_subject_ext'
execute #countrows @t='oe_purchase_order'
execute #countrows @t='ac_invoice_ext'
execute #countrows @t='ev_location_room_x_setup_ext'
execute #countrows @t='co_call2action_detail'
execute #countrows @t='ad_contract_x_contact'
execute #countrows @t='co_organization_product'
execute #countrows @t='co_request_action'
execute #countrows @t='md_metadata_lock'
execute #countrows @t='su_fulfillment_bpa_ext'
execute #countrows @t='md_object_related_control'
execute #countrows @t='ce_course_type_ext'
execute #countrows @t='md_web_posting_rating'
execute #countrows @t='ev_event_cancel_fee'
execute #countrows @t='su_fulfillment_group_ext'
execute #countrows @t='md_sync_sql_log_status'
execute #countrows @t='ac_credit_reason'
execute #countrows @t='oe_bundle_component'
execute #countrows @t='co_fax_error_ext'
execute #countrows @t='tm_expense_type'
execute #countrows @t='oe_product_affiliation_commission'
execute #countrows @t='co_task'
execute #countrows @t='co_correspondence'
execute #countrows @t='gr_congress_state_committee_roster'
execute #countrows @t='oe_price_term'
execute #countrows @t='am_surveyors_peer_evaluation_ext'
execute #countrows @t='ac_discount_temp'
execute #countrows @t='su_request_type_ext'
execute #countrows @t='co_chapter_x_dg_topic_group_ext'
execute #countrows @t='co_survey_response'
execute #countrows @t='md_web_faq_category_ext'
execute #countrows @t='am_surveyor_status_ext'
execute #countrows @t='co_assignment_subject'
execute #countrows @t='su_subscription_renewal_process'
execute #countrows @t='client_scouts_program'
execute #countrows @t='ev_location_setup_category_ext'
execute #countrows @t='md_dynamic_form_x_column'
execute #countrows @t='oe_inventory_adjustment_ext'
execute #countrows @t='ce_course_x_location'
execute #countrows @t='ac_exchange_rate_ext'
execute #countrows @t='co_fax_ext'
execute #countrows @t='ev_registration_dem_ext'
execute #countrows @t='ad_classified_ad_x_publication_ext'
execute #countrows @t='ev_event_category'
execute #countrows @t='ce_certificant_status'
execute #countrows @t='co_customer'
execute #countrows @t='aw_award_header'
execute #countrows @t='oe_product_x_vendor'
execute #countrows @t='ev_location_setup_ext'
execute #countrows @t='ce_cert_program_type'
execute #countrows @t='client_scouts_emergency_contact_info'
execute #countrows @t='np_recognition_level_ext'
execute #countrows @t='co_email'
execute #countrows @t='ev_location_type'
execute #countrows @t='md_web_faq_category'
execute #countrows @t='oe_merchandise'
execute #countrows @t='co_chapter_type'
execute #countrows @t='co_call2action_detail_ext'
execute #countrows @t='tm_project_resource_ext'
execute #countrows @t='ac_invoice_detail_ext'
execute #countrows @t='md_web_link'
execute #countrows @t='ev_location_type_ext'
execute #countrows @t='oe_shipping_product'
execute #countrows @t='ex_booth_personnel_fee_ext'
execute #countrows @t='ab_author'
execute #countrows @t='ev_event_location'
execute #countrows @t='jb_job_function_ext'
execute #countrows @t='client_scouts_activity'
execute #countrows @t='co_individual_dem'
execute #countrows @t='ad_classified_ad_x_publication'
execute #countrows @t='mb_type_status_x_oe_price'
execute #countrows @t='fw_synchronization_keyxref'
execute #countrows @t='ex_exhibitor_x_co_customer'
execute #countrows @t='sf_opportunity_source_ext'
execute #countrows @t='md_sync_sql_error_log'
execute #countrows @t='oe_bundle_x_product_type_ext'
execute #countrows @t='co_chapter_ext'
execute #countrows @t='ex_booth_number'
execute #countrows @t='co_customer_product_review'
execute #countrows @t='client_scouts_activity_x_co_customer'
execute #countrows @t='aw_award_header_ext'
execute #countrows @t='mb_association'
execute #countrows @t='oe_order_detail_schedule'
execute #countrows @t='ce_individual_x_course_ext'
execute #countrows @t='ev_track_cancel_fee'
execute #countrows @t='md_workflow_rule'
execute #countrows @t='ev_location_x_co_individual_ext'
execute #countrows @t='md_dynamic_form_extension'
execute #countrows @t='ce_provider_x_course_type_ext'
execute #countrows @t='fw_user_x_persona'
execute #countrows @t='ec_payment_ext'
execute #countrows @t='md_report_x_user'
execute #countrows @t='fw_taxonomy_detail_ext'
execute #countrows @t='co_customer_wish_list'
execute #countrows @t='client_scouts_equipment'
execute #countrows @t='ac_refund'
execute #countrows @t='ts_stored_procedure_task'
execute #countrows @t='md_web_posting_document'
execute #countrows @t='ev_event_speaker_handout'
execute #countrows @t='gr_congress_fed_data_committee'
execute #countrows @t='ac_miscellaneous_counter'
execute #countrows @t='tm_project_resource'
execute #countrows @t='co_individual_type_ext'
execute #countrows @t='client_scouts_individual_x_volunteer_program'
execute #countrows @t='ev_location_x_setup'
execute #countrows @t='md_web'
execute #countrows @t='ac_return'
execute #countrows @t='ce_ceu_type_ext'
execute #countrows @t='co_region_ext'
execute #countrows @t='co_customer_x_customer'
execute #countrows @t='mk_mailing_list'
execute #countrows @t='co_demographic_item_ext'
execute #countrows @t='client_scouts_equipment_x_co_customer'
execute #countrows @t='ac_invoice_detail_additional'
execute #countrows @t='co_email_optout_ext'
execute #countrows @t='fw_user_email_alias'
execute #countrows @t='ce_exam_ext'
execute #countrows @t='oe_inventory_adjustment'
execute #countrows @t='su_fulfillment_ext'
execute #countrows @t='ev_location_x_setup_ext'
execute #countrows @t='oe_bundle'
execute #countrows @t='ws_activity_log'
execute #countrows @t='ev_event_x_co_document_ext'
execute #countrows @t='ev_event_session_room_x_setup'
execute #countrows @t='client_scouts_service'
execute #countrows @t='su_classification_ext'
execute #countrows @t='ac_project'
execute #countrows @t='ex_booth_number_preference'
execute #countrows @t='co_assignment_x_customer'
execute #countrows @t='oe_discount_product'
execute #countrows @t='aw_award_type_ext'
execute #countrows @t='ce_exam_score_history_ext'
execute #countrows @t='sf_territory_assignment'
execute #countrows @t='am_surveyor_type_x_status_ext'
execute #countrows @t='client_scouts_service_x_co_customer'
execute #countrows @t='co_email_error_archive_ext'
execute #countrows @t='co_individual_type'
execute #countrows @t='gn_program'
execute #countrows @t='ex_booth_personnel_fee'
execute #countrows @t='mb_member_drop_process_ext'
execute #countrows @t='ce_ceu_type'
execute #countrows @t='su_fulfillment_group'
execute #countrows @t='co_customer_x_phone_ext'
execute #countrows @t='ev_event_speaker'
execute #countrows @t='co_demographic_list_value'
execute #countrows @t='mb_dues_calc'
execute #countrows @t='ce_requirements_ext'
execute #countrows @t='ac_ledger'
execute #countrows @t='md_table_list_from'
execute #countrows @t='oe_product_package'
execute #countrows @t='ex_priority_point_group_ext'
execute #countrows @t='ac_invoice_detail_term'
execute #countrows @t='ev_event_x_co_document'
execute #countrows @t='oe_vendor_ext'
execute #countrows @t='aw_award_entry_status'
execute #countrows @t='tm_expense_ext'
execute #countrows @t='mb_committee_nomination'
execute #countrows @t='ex_priority_point_type'
execute #countrows @t='am_surveyor_type'
execute #countrows @t='ev_session_cancel_fee'
execute #countrows @t='mb_calculation_result_ext'
execute #countrows @t='md_search_table'
execute #countrows @t='md_page_access_archive'
execute #countrows @t='mb_committee_minutes_ext'
execute #countrows @t='ev_registrant_group_ext'
execute #countrows @t='ev_session_fee'
execute #countrows @t='oe_publication_ext'
execute #countrows @t='ex_show_x_priority_point_type'
execute #countrows @t='md_report_request'
execute #countrows @t='ts_scheduled_task_history'
execute #countrows @t='sf_opportunity_competitor_ext'
execute #countrows @t='ev_transfer_fee'
execute #countrows @t='np_gift_ext'
execute #countrows @t='mb_committee_nomination_ext'
execute #countrows @t='mb_member_benefits_ext'
execute #countrows @t='jb_job_function'
execute #countrows @t='xx_template'
execute #countrows @t='ad_rate_card_category_ext'
execute #countrows @t='np_premium'
execute #countrows @t='gr_congress_fed_dist_office'
execute #countrows @t='co_individual_x_organization_ext'
execute #countrows @t='co_customer_x_address'
execute #countrows @t='oe_warehouse_ext'
execute #countrows @t='ev_registrant_type_ext'
execute #countrows @t='ce_provider_x_course_ext'
execute #countrows @t='oe_order_detail'
execute #countrows @t='ce_cert_program_type_ext'
execute #countrows @t='ev_evaluation'
execute #countrows @t='mb_committee_x_position_ext'
execute #countrows @t='co_individual'
execute #countrows @t='fw_taxonomy_header'
execute #countrows @t='co_demographic_group_ext'
execute #countrows @t='ce_cert_program_ext'
execute #countrows @t='md_query_detail'
execute #countrows @t='fw_group_x_link'
execute #countrows @t='ac_invoice_counter'
execute #countrows @t='ce_exam_grader'
execute #countrows @t='ev_event_speaker_type'
execute #countrows @t='ce_cert_program_fee_ext'
execute #countrows @t='oe_product_complement'
execute #countrows @t='client_scouts_rlt_x_rlt'
execute #countrows @t='ex_exhibitor_booth_shared'
execute #countrows @t='ad_rate_card'
execute #countrows @t='md_web_faq_ext'
execute #countrows @t='su_title_ext'
execute #countrows @t='np_donor_funds_raised_ext'
execute #countrows @t='ad_advertisement_ext'
execute #countrows @t='ev_session_ext'
execute #countrows @t='aw_award_winner_type_ext'
execute #countrows @t='fw_user_x_link'
execute #countrows @t='ce_credits'
execute #countrows @t='ac_batch'
execute #countrows @t='ex_exhibitor_booth'
execute #countrows @t='ac_company_x_currency_ext'
execute #countrows @t='ad_classified_ad'
execute #countrows @t='aw_award_entry_status_ext'
execute #countrows @t='ce_requirements'
execute #countrows @t='ex_exhibitor_x_co_customer_ext'
execute #countrows @t='client_scouts_approval_record'
execute #countrows @t='ev_session_track_type'
execute #countrows @t='mb_member_status_change_process_ext'
execute #countrows @t='oe_discount_product_x_product'
execute #countrows @t='mb_membership_audit_trail_ext'
execute #countrows @t='oe_tax_product_ext'
execute #countrows @t='ac_invoice'
execute #countrows @t='co_customer_x_fax_ext'
execute #countrows @t='aw_award_sponsor_ext'
execute #countrows @t='oe_order_detail_additional_ext'
execute #countrows @t='am_surveyor_status'
execute #countrows @t='ad_number_placement_ext'
execute #countrows @t='md_object'
execute #countrows @t='ex_priority_point_detail_ext'
execute #countrows @t='oe_fulfillment_inventory_cogs'
execute #countrows @t='md_web_posting_x_posting'
execute #countrows @t='lm_data_import_ext'
execute #countrows @t='client_scouts_role_x_execute_methods'
execute #countrows @t='tm_time_ext'
execute #countrows @t='ev_session_x_track'
execute #countrows @t='aw_award_type'
execute #countrows @t='co_magnetmail_unsubscribe_ext'
execute #countrows @t='co_interest_code_ext'
execute #countrows @t='ac_company_x_currency'
execute #countrows @t='oe_price'
execute #countrows @t='tm_expense'
execute #countrows @t='oe_fulfillment'
execute #countrows @t='co_contact_request'
execute #countrows @t='co_correspondence_template_ext'
execute #countrows @t='aw_award_entry_ext'
execute #countrows @t='co_degree_type_ext'
execute #countrows @t='mb_type_status_x_oe_price_ext'
execute #countrows @t='su_subscription_issue_ext'
execute #countrows @t='client_scouts_role_x_forms'
execute #countrows @t='oe_product_x_vendor_ext'
execute #countrows @t='ev_session_x_track_ext'
execute #countrows @t='client_scouts_org_merge_history'
execute #countrows @t='gr_congress'
execute #countrows @t='co_keyword_ext'
execute #countrows @t='ex_show_sponsor'
execute #countrows @t='mb_membership_terminate_reason'
execute #countrows @t='oe_product_type_ext'
execute #countrows @t='cm_group_item'
execute #countrows @t='md_lookup_xref'
execute #countrows @t='co_related_association'
execute #countrows @t='ce_certificate_number_counter'
execute #countrows @t='ce_course_x_event'
execute #countrows @t='sf_commission_schedule_ext'
execute #countrows @t='co_customer_x_gr_congress'
execute #countrows @t='dg_thread'
execute #countrows @t='mb_association_ext'
execute #countrows @t='fw_taxonomy_category'
execute #countrows @t='md_web_section_x_link'
execute #countrows @t='co_degree_area'
execute #countrows @t='oe_inventory_reorder'
execute #countrows @t='ev_transfer_fee_ext'
execute #countrows @t='np_pledge_renewal_process_header_ext'
execute #countrows @t='ws_activity_log_ext'
execute #countrows @t='ev_track_ext'
execute #countrows @t='fw_persona_x_link'
execute #countrows @t='am_surveyors_peer_evaluation'
execute #countrows @t='co_email_optout'
execute #countrows @t='co_magnetmail_fax_tracking_ext'
execute #countrows @t='ex_booth_number_preference_ext'
execute #countrows @t='ev_event_location_room_block_ext'
execute #countrows @t='oe_product_complement_ext'
execute #countrows @t='dg_thread_ext'
execute #countrows @t='ev_event_faculty'
execute #countrows @t='ad_classified_ad_ext'
execute #countrows @t='co_phone'
execute #countrows @t='ev_location_setup'
execute #countrows @t='client_scouts_police_records_check'
execute #countrows @t='am_accreditation_review_ext'
execute #countrows @t='oe_inventory_reorder_ext'
execute #countrows @t='ce_exam'
execute #countrows @t='ab_abstract_reviewer_x_submission'
execute #countrows @t='ac_invoice_detail_additional_ext'
execute #countrows @t='aw_award_sponsor'
execute #countrows @t='fw_system_option_entity'
execute #countrows @t='sf_opportunity_type'
execute #countrows @t='am_accreditation_customeraffliates'
execute #countrows @t='fw_error_message'
execute #countrows @t='md_workflow_task_value'
execute #countrows @t='ce_provider_x_course'
execute #countrows @t='oe_bundle_x_product_type'
execute #countrows @t='dg_topic_ext'
execute #countrows @t='mb_member_dues_renewal_process'
execute #countrows @t='am_surveyor_type_x_status'
execute #countrows @t='co_organization_dem'
execute #countrows @t='aw_award_stage'
execute #countrows @t='su_job_function_ext'
execute #countrows @t='am_accreditation_customeraffliates_ext'
execute #countrows @t='xx_template_ext'
execute #countrows @t='aw_award_status_ext'
execute #countrows @t='co_survey_detail'
execute #countrows @t='co_chapter_x_document_ext'
execute #countrows @t='jb_job_experience_ext'
execute #countrows @t='np_donor_funds_raised'
execute #countrows @t='ce_exam_x_location'
execute #countrows @t='am_accreditation_ext'
execute #countrows @t='ev_event_credit'
execute #countrows @t='md_web_faq_subject'
execute #countrows @t='aw_award_winner_type'
execute #countrows @t='mb_committee_x_customer'
execute #countrows @t='oe_shipping_product_ext'
execute #countrows @t='co_address_type_ext'
execute #countrows @t='co_fax_type_ext'
execute #countrows @t='am_accreditation_fee'
execute #countrows @t='co_award_ext'
execute #countrows @t='co_customer_x_gr_congress_fed'
execute #countrows @t='ex_priority_point_type_ext'
execute #countrows @t='ad_insertion_order_ext'
execute #countrows @t='md_dynamic_form_child'
execute #countrows @t='tm_project_ext'
execute #countrows @t='client_scouts_participation_area'
execute #countrows @t='co_demographic_group'
execute #countrows @t='md_report_parameter'
execute #countrows @t='am_accreditation_fee_ext'
execute #countrows @t='co_award'
execute #countrows @t='co_customer_x_gr_congress_fed_ext'
execute #countrows @t='mb_dues_calc_detail'
execute #countrows @t='md_web_content_x_link'
execute #countrows @t='co_interest_ext'
execute #countrows @t='client_scouts_recognition_list_x_co_customer'
execute #countrows @t='ac_credit_counter'
execute #countrows @t='fw_taxonomy_detail'
execute #countrows @t='mb_membership_audit_trail'
execute #countrows @t='co_chapter_x_document'
execute #countrows @t='jb_job_experience'
execute #countrows @t='ab_abstract_reviewer'
execute #countrows @t='ad_number_placement'
execute #countrows @t='co_customer_x_gr_congress_fed_relationship'
execute #countrows @t='co_voting_history'
execute #countrows @t='co_magnetmail_unsubscribe'
execute #countrows @t='co_call2action_batch_code'
execute #countrows @t='np_pledge_type_ext'
execute #countrows @t='co_assignment_ext'
execute #countrows @t='co_keyword_xref_ext'
execute #countrows @t='co_country_ext'
execute #countrows @t='np_pledge_renewal_process_header'
execute #countrows @t='co_call2action'
execute #countrows @t='co_degree_area_ext'
execute #countrows @t='am_accreditation_status_ext'
execute #countrows @t='co_customer_x_gr_congress_fed_relationship_ext'
execute #countrows @t='md_wizard'
execute #countrows @t='ex_priority_point_group'
execute #countrows @t='ac_company_ext'
execute #countrows @t='oe_product_affiliation_role'
execute #countrows @t='oe_publication'
execute #countrows @t='md_web_options'
execute #countrows @t='co_organization_product_type_ext'
execute #countrows @t='co_customer_x_gr_congress_state'
execute #countrows @t='np_major_gift_status_ext'
execute #countrows @t='mb_membership_proxy_ext'
execute #countrows @t='ce_provider_x_course_type'
execute #countrows @t='client_scouts_member_registration'
execute #countrows @t='co_assignment_role_ext'
execute #countrows @t='ac_company'
execute #countrows @t='ce_ceu_credit_generate_header_ext'
execute #countrows @t='ac_invoice_detail_term_ext'
execute #countrows @t='md_web_posting_group_ext'
execute #countrows @t='ev_session_track_type_ext'
execute #countrows @t='ex_exhibitor_product_type'
execute #countrows @t='ws_security'
execute #countrows @t='sm_group'
execute #countrows @t='ac_credit_reason_ext'
execute #countrows @t='md_web_faq_subject_ext'
execute #countrows @t='am_accreditation_type_ext'
execute #countrows @t='co_customer_x_gr_congress_state_ext'
execute #countrows @t='md_wizard_form_button'
execute #countrows @t='np_pledge_type'
execute #countrows @t='client_scouts_code_of_conduct'
execute #countrows @t='co_magnetmail_fax_tracking'
execute #countrows @t='oe_price_x_ac_gl_account'
execute #countrows @t='ex_exhibitor_ext'
execute #countrows @t='co_fax'
execute #countrows @t='ce_certificant_ext'
execute #countrows @t='sm_group_ext'
execute #countrows @t='am_accreditation_type_x_status'
execute #countrows @t='co_customer_x_gr_congress_state_relationship'
execute #countrows @t='ad_contract_status_ext'
execute #countrows @t='co_contact_request_ext'
execute #countrows @t='client_scouts_code_of_conduct_x_co_individual'
execute #countrows @t='ce_cert_program_fee'
execute #countrows @t='ac_invoice_detail_term_requalification_ext'
execute #countrows @t='am_accreditation_type_x_status_ext'
execute #countrows @t='co_customer_x_gr_congress_state_relationship_ext'
execute #countrows @t='np_major_gift_status'
execute #countrows @t='oe_price_x_ac_gl_account_ext'
execute #countrows @t='ac_payment_method_x_currency_ext'
execute #countrows @t='oe_order_ext'
execute #countrows @t='ac_return_counter'
execute #countrows @t='fw_user_ip_address'
execute #countrows @t='co_survey_type'
execute #countrows @t='mb_dues_calc_variables_ext'
execute #countrows @t='mb_member_drop_process_header_ext'
execute #countrows @t='co_contact_response_ext'
execute #countrows @t='oe_discount_product_ext'
execute #countrows @t='co_phone_type_ext'
execute #countrows @t='jb_job_bank'
execute #countrows @t='aw_award_category_ext'
execute #countrows @t='oe_package'
execute #countrows @t='am_accreditation_x_customer_ext'
execute #countrows @t='client_scouts_security_information'
execute #countrows @t='ex_show_x_booth'
execute #countrows @t='oe_product_substitute_ext'
execute #countrows @t='co_organization'
execute #countrows @t='mb_member_dues_renewal_batch_log'
execute #countrows @t='ce_credits_ext'
execute #countrows @t='ac_invoice_detail_term_requalification'
execute #countrows @t='gr_congress_fed_committee_roster_ext'
execute #countrows @t='mb_committee'
execute #countrows @t='co_issue_tracking'
execute #countrows @t='md_web_album'
execute #countrows @t='np_recognition_level'
execute #countrows @t='co_correspondence_ext'
execute #countrows @t='ac_payment_method_x_currency'
execute #countrows @t='oe_product_affiliation_ext'
execute #countrows @t='sf_opportunity_source'
execute #countrows @t='mb_member_dues_history_ext'
execute #countrows @t='am_survey_scope_ext'
execute #countrows @t='co_interest'
execute #countrows @t='ce_discipline_ext'
execute #countrows @t='mb_committee_nomination_status_ext'
execute #countrows @t='co_keyword_xref'
execute #countrows @t='aw_award_status'
execute #countrows @t='md_recent_activity'
execute #countrows @t='ac_misc_transaction_detail'
execute #countrows @t='am_survey_team'
execute #countrows @t='gr_congress_fed_data_committee_ext'
execute #countrows @t='fw_system_option'
execute #countrows @t='mk_mailing_list_detail'
execute #countrows @t='fw_favorite_page'
execute #countrows @t='ex_booth_personnel'
execute #countrows @t='client_scouts_co_individual_x_participation'
execute #countrows @t='ac_currency'
execute #countrows @t='ad_rate_card_category'
execute #countrows @t='co_organization_product_ext'
execute #countrows @t='co_degree_specialty_ext'
execute #countrows @t='am_survey_team_ext'
execute #countrows @t='co_magnetmail_link_tracking'
execute #countrows @t='co_document_classification_ext'
execute #countrows @t='ev_event_staff_type'
execute #countrows @t='co_chapter'
execute #countrows @t='dtproperties'
execute #countrows @t='mb_member_type_ext'
execute #countrows @t='aw_award_sponsor_fee_ext'
execute #countrows @t='oe_product_affiliation_role_ext'
execute #countrows @t='ex_exhibitor_product'
execute #countrows @t='fw_user_x_group'
execute #countrows @t='ce_exam_fee_ext'
execute #countrows @t='ac_credit_ext'
execute #countrows @t='am_survey_type'
execute #countrows @t='gr_congress_fed_dist_office_ext'
execute #countrows @t='ev_registrant_ext'
execute #countrows @t='co_source_code_ext'
execute #countrows @t='np_major_gift'
execute #countrows @t='ac_company_x_gl_account_ext'
execute #countrows @t='ac_customer_payment_info_ext'
execute #countrows @t='md_whois'
execute #countrows @t='co_document_ext'
execute #countrows @t='mb_committee_nomination_status'
execute #countrows @t='co_request_document'
execute #countrows @t='tm_project_x_work_type_ext'
execute #countrows @t='fw_group_table_privilege'
execute #countrows @t='mb_dues'
execute #countrows @t='ac_collection_status_ext'
execute #countrows @t='di_document_word'
execute #countrows @t='md_query_header'
execute #countrows @t='co_demographic_group_x_item'
execute #countrows @t='am_survey_type_ext'
execute #countrows @t='gr_congress_fed_ext'
execute #countrows @t='np_pledge_renewal_process_detail_ext'
execute #countrows @t='co_demographic_value'
execute #countrows @t='np_appeal'
execute #countrows @t='mb_member_type_x_co_relationship_type_ext'
execute #countrows @t='mb_committee_position'
execute #countrows @t='ac_payment_method'
execute #countrows @t='ev_event_x_product_ext'
execute #countrows @t='ad_insertion_order_detail_additional_ext'
execute #countrows @t='co_chapter_x_ac_invoice_ext'
execute #countrows @t='ev_event_x_registrant_type'
execute #countrows @t='ex_exhibitor'
execute #countrows @t='gr_congress_fed_staff'
execute #countrows @t='ad_invoice_group'
execute #countrows @t='co_request_action_ext'
execute #countrows @t='ac_batch_export_ext'
execute #countrows @t='aw_award_sponsor_fee'
execute #countrows @t='wf_workflow'
execute #countrows @t='co_customer_od_map'
execute #countrows @t='am_survey_x_accreditation_ext'
execute #countrows @t='gr_congress_fed_staff_ext'
execute #countrows @t='co_magnetmail_email_tracking_ext'
execute #countrows @t='co_website_ext'
execute #countrows @t='aw_award_entry_x_co_document_ext'
execute #countrows @t='ac_exchange_rate'
execute #countrows @t='oe_order_detail_ext'
execute #countrows @t='ac_collection_status'
execute #countrows @t='ac_media_type_ext'
execute #countrows @t='aw_award_media_ext'
execute #countrows @t='co_organization_product_type'
execute #countrows @t='lm_list_detail'
execute #countrows @t='co_address_od_map'
execute #countrows @t='md_report_parameter_mapping'
execute #countrows @t='su_industry'
execute #countrows @t='sf_opportunity_competitor'
execute #countrows @t='np_pledge_renewal_process_detail'
execute #countrows @t='np_constituent_ext'
execute #countrows @t='co_customer_x_gr_congress_relationship'
execute #countrows @t='co_request_activity_type_ext'
execute #countrows @t='ev_registrant_room_request'
execute #countrows @t='ev_event_x_product'
execute #countrows @t='aw_award_judge'
execute #countrows @t='co_chapter_x_ac_invoice'
execute #countrows @t='am_surveyor'
execute #countrows @t='co_phone_od_map'
execute #countrows @t='am_surveyor_ext'
execute #countrows @t='md_dynamic_form_child_link'
execute #countrows @t='mb_committee_x_position'
execute #countrows @t='co_customer_x_customer_ext'
execute #countrows @t='np_product_code'
execute #countrows @t='mb_member_type_x_co_relationship_type'
execute #countrows @t='co_request_comment'
execute #countrows @t='am_surveyor_x_document_ext'
execute #countrows @t='oe_package_ext'
execute #countrows @t='ac_batch_export'
execute #countrows @t='co_call2action_campaign_ext'
execute #countrows @t='oe_vendor'
execute #countrows @t='client_scouts_org_fee_x_date'
execute #countrows @t='ac_batch_x_fw_group'
execute #countrows @t='am_survey_x_accreditation'
execute #countrows @t='ec_shopping_cart_items_ext'
execute #countrows @t='md_query_tracking'
execute #countrows @t='co_fax_od_map'
execute #countrows @t='ev_event_ext'
execute #countrows @t='am_surveyor_roles'
execute #countrows @t='md_table'
execute #countrows @t='gr_congress_state_committee_roster_ext'
execute #countrows @t='co_request_comment_ext'
execute #countrows @t='dg_topic_group_ext'
execute #countrows @t='co_phone_type'
execute #countrows @t='ad_rate_card_x_publication_ext'
execute #countrows @t='co_demographic_item'
execute #countrows @t='aw_award_category'
execute #countrows @t='ac_adjustment_detail'
execute #countrows @t='md_web_posting_ext'
execute #countrows @t='co_email_od_map'
execute #countrows @t='md_dynamic_form'
execute #countrows @t='am_surveyor_roles_ext'
execute #countrows @t='gr_congress_state_data_committee'
execute #countrows @t='ev_event_staff'
execute #countrows @t='ab_abstract_status_ext'
execute #countrows @t='ac_adjustment_counter'
execute #countrows @t='client_scouts_external_volunteer_screening'
execute #countrows @t='np_constituent'
execute #countrows @t='md_web_posting_group'
execute #countrows @t='ac_invoice_tax_temp'
execute #countrows @t='co_website_od_map'
execute #countrows @t='gr_congress_state_data_committee_ext'
execute #countrows @t='mb_member_status_change_process'
execute #countrows @t='np_corp_matching'
execute #countrows @t='md_object_related'
execute #countrows @t='np_planned_giving'
execute #countrows @t='co_request_document_ext'
execute #countrows @t='tm_project_task_ext'
execute #countrows @t='client_scouts_postal_long_lat'
execute #countrows @t='ac_payment_detail'
execute #countrows @t='client_scouts_course_catalogue_x_external'
execute #countrows @t='ab_abstract_reviewer_response'
execute #countrows @t='co_document'
execute #countrows @t='co_note_od_map'
execute #countrows @t='ce_course_fee_ext'
execute #countrows @t='cs_case_ext'
execute #countrows @t='ce_course_x_program_ext'
execute #countrows @t='ac_company_x_gl_account'
execute #countrows @t='md_web_link_delete'
execute #countrows @t='ac_credit_detail_ext'
execute #countrows @t='am_surveyor_x_survey_ext'
execute #countrows @t='np_gift'
execute #countrows @t='gr_congress_state_dist_office'
execute #countrows @t='mb_member_drop_process'
execute #countrows @t='mb_dues_ext'
execute #countrows @t='np_donor_category'
execute #countrows @t='co_request_origin'
execute #countrows @t='ce_discipline'
execute #countrows @t='dg_topic_group'
execute #countrows @t='np_wealthengine_results_ext'
execute #countrows @t='oe_discount_product_x_product_ext'
execute #countrows @t='ac_ar_period_scheduler'
execute #countrows @t='aw_award_entry_contact_ext'
execute #countrows @t='ex_complementary_products_fee'
execute #countrows @t='mb_member_od_map'
execute #countrows @t='cs_case_fee'
execute #countrows @t='ad_rate_card_ext'
execute #countrows @t='gr_congress_state_dist_office_ext'
execute #countrows @t='ac_payment_info_ext'


-- make fix stmts 
SELECT 'select * from sys.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('''+ tname +'''), NULL, NULL, NULL) indexstats'  
FROM ##ROWCOUNTS 
WHERE  COUNT > 10000 

SELECT 'ALTER INDEX ALL ON DBO.' + tname + ' REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!'  
FROM ##ROWCOUNTS 
WHERE  COUNT > 10000 

select * from sys.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('md_page_access'), NULL, NULL, NULL) indexstats
select * from sys.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('fw_group_column_privilege'), NULL, NULL, NULL) indexstats
select * from sys.dm_db_index_physical_stats(DB_ID(), OBJECT_ID('client_scouts_compliance_tracking'), NULL, NULL, NULL) indexstats

/*
database_id object_id   index_id    partition_number index_type_desc                                              alloc_unit_type_desc                                         index_depth index_level avg_fragmentation_in_percent fragment_count       avg_fragment_size_in_pages page_count           avg_page_space_used_in_percent record_count         ghost_record_count   version_ghost_record_count min_record_size_in_bytes max_record_size_in_bytes avg_record_size_in_bytes forwarded_record_count compressed_page_count
----------- ----------- ----------- ---------------- ------------------------------------------------------------ ------------------------------------------------------------ ----------- ----------- ---------------------------- -------------------- -------------------------- -------------------- ------------------------------ -------------------- -------------------- -------------------------- ------------------------ ------------------------ ------------------------ ---------------------- ---------------------
7           10456553    1           1                CLUSTERED INDEX                                              IN_ROW_DATA                                                  4           0           94.0203167956582             186418               1.05560085399479           196783               NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    2           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  3           0           99.156541821468              29876                1.00003347168296           29877                NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    3           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           98.6046511627907             10008                1.00969224620304           10105                NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    4           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           97.4696356275304             8710                 1.02089552238806           8892                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    5           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           86.0278372591007             6549                 1.14093754771721           7472                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    6           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           97.2562689755988             8697                 1.02253650684144           8893                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    7           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           97.3462273698415             8698                 1.02241894688434           8893                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    8           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           97.4246513720198             8708                 1.02112999540652           8892                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    9           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           98.5266112057733             9891                 1.00869477302598           9977                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    10          1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           98.5216949726344             17604                1.00675982731197           17723                NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           10456553    11          1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  4           0           97.2302219210571             11525                1.02438177874187           11806                NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL

(11 row(s) affected)

database_id object_id   index_id    partition_number index_type_desc                                              alloc_unit_type_desc                                         index_depth index_level avg_fragmentation_in_percent fragment_count       avg_fragment_size_in_pages page_count           avg_page_space_used_in_percent record_count         ghost_record_count   version_ghost_record_count min_record_size_in_bytes max_record_size_in_bytes avg_record_size_in_bytes forwarded_record_count compressed_page_count
----------- ----------- ----------- ---------------- ------------------------------------------------------------ ------------------------------------------------------------ ----------- ----------- ---------------------------- -------------------- -------------------------- -------------------- ------------------------------ -------------------- -------------------- -------------------------- ------------------------ ------------------------ ------------------------ ---------------------- ---------------------
7           23579768    1           1                CLUSTERED INDEX                                              IN_ROW_DATA                                                  3           0           81.2163404702483             12549                1.21332377081839           15226                NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           23579768    2           1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  3           0           20.1559020044543             937                  4.79188900747065           4490                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           23579768    13          1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  3           0           80.9139784946236             2130                 1.22253521126761           2604                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           23579768    14          1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  3           0           80.6923076923077             2124                 1.2241054613936            2600                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL
7           23579768    15          1                NONCLUSTERED INDEX                                           IN_ROW_DATA                                                  3           0           80.1689313257437             2207                 1.23380154055279           2723                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL

(5 row(s) affected)

database_id object_id   index_id    partition_number index_type_desc                                              alloc_unit_type_desc                                         index_depth index_level avg_fragmentation_in_percent fragment_count       avg_fragment_size_in_pages page_count           avg_page_space_used_in_percent record_count         ghost_record_count   version_ghost_record_count min_record_size_in_bytes max_record_size_in_bytes avg_record_size_in_bytes forwarded_record_count compressed_page_count
----------- ----------- ----------- ---------------- ------------------------------------------------------------ ------------------------------------------------------------ ----------- ----------- ---------------------------- -------------------- -------------------------- -------------------- ------------------------------ -------------------- -------------------- -------------------------- ------------------------ ------------------------ ------------------------ ---------------------- ---------------------
7           33512740    1           1                CLUSTERED INDEX                                              IN_ROW_DATA                                                  3           0           98.7973541791942             1663                 1                          1663                 NULL                           NULL                 NULL                 NULL                       NULL                     NULL                     NULL                     NULL                   NULL

(1 row(s) affected)

*/



/* 

ALTER INDEX ALL ON DBO.md_page_access REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.fw_group_column_privilege REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_compliance_tracking REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!

ALTER INDEX ALL ON DBO.can_post_codes REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_activity REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_organization_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment_info REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_course_catalogue_x_co_customer REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_report_request_key_list REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!

ALTER INDEX ALL ON DBO.ac_payment_detail_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_member_account REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_invoice_detail REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_individual_x_organization REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_activity_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_individual_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_experimental_registration REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_online_transaction_error_log REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_online_user_exception_log REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.fw_change_log REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_address REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_upgrade_deleted_metadata REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_avectra_informz_email_tracking REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_avectra_informz_email_tracking_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_dynamic_form_control REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_address_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_fax REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_batch_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_address_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_batch_x_fw_group_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment_counter REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_email_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_address_change_log REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_workflow_task_log REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_privilege REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_address_change_log_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_column REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_volunteer_screening_reference REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_phone_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_volunteer_screening REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_phone REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_invoice_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_fax_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_email REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_invoice_detail_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_customer REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_phone_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_ledger REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.md_page_access_archive REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_individual_x_organization_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_address REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_individual REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.fw_group_x_link REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_invoice_counter REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_batch REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_approval_record REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_invoice REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_fax_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_phone REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_recognition_list_x_co_customer REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_member_registration REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_fax REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_code_of_conduct_x_co_individual REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_organization REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.fw_group_table_privilege REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.co_customer_x_customer_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_org_fee_x_date REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_batch_x_fw_group REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_external_volunteer_screening REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.client_scouts_postal_long_lat REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment_detail REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!
ALTER INDEX ALL ON DBO.ac_payment_info_ext REORGANIZE ;  --- RECOMPUTE OUT OF DATE STATS !!!

*/








