

USE SMTR 

; with info as ( 
SELECT T.*, hist.TABLE_NAME as HistoryTableName
FROM INFORMATION_SCHEMA.TABLES T 
LEFT JOIN INFORMATION_SCHEMA.TABLES HIST ON T.TABLE_NAME + 'History' = HIST.TABLE_NAME and HIST.TABLE_SCHEMA = T.TABLE_SCHEMA
WHERE T.TABLE_SCHEMA = 'OP' 
and T.TABLE_NAME NOT LIKE '%History%'
) 
SELECT * FROM INFO WHERE HistoryTableName IS NULL 

